---

all:
  children:
    cluster:
      vars:
        makeatstate_secrets_stack_name: makeatstate
        makeatstate_mail_from: "root@{{ inventory_hostname }}"
        makeatstate_mail_smtp_host: express.mail.msu.edu
        makeatstate_oauth2_issuer: "https://auth.msu.edu/oauth2/default"
        makeatstate_oauth2_redirect_url:
          "https://{{ inventory_hostname }}\
           /?t=okta-authorization-code-callback"
        makeatstate_use_letsencrypt: true
      children:
        prod:
          vars:
            deploy_gitlab_host: gitlab.msu.edu
            deploy_gitlab_project: msu-libraries/web-services/makeatstate
            deploy_user: deploy
            deploy_sudoers: |
              %{{ deploy_user }} ALL = (root) NOPASSWD: ALL
            deploy_key_tag: makeatstate
          hosts:
            makeatstate.lib.msu.edu:
              makeatstate_alternative_hostnames:
                - 3dprime.lib.msu.edu
              makeatstate_oauth2_client_id: "0oala7q1ivRCA1Q6m357"
        secondary_stacks:
          children:
            review:
              hosts:
                review.makeatstate.lib.msu.edu:
                  makeatstate_oauth2_client_id: ~
                test.makeatstate.lib.msu.edu:
                  makeatstate_use_letsencrypt: false
                  makeatstate_oauth2_client_id: ~
