---

- name: Update Apt repository (Ubuntu).
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Install package for docker_stack module.
  package:
    name:
      - python3-jsondiff    # Needed for docker_stack module.
    state: present

- name: Initialize a new swarm with default parameters.
  docker_swarm:
    advertise_addr: lo
    listen_addr: lo
    state: present
